
-- CẢNH BÁO: Sử dụng khoảng trắng và chữ hoa trong tên file có thể gây ra
-- lỗi trên một số hệ thống máy chủ web (web server) do yêu cầu mã hóa URL.
-- Vui lòng đảm bảo máy chủ của bạn hỗ trợ cấu trúc file này.

INSERT INTO image (product_id, image_url) VALUES
                                              (1, '/image/ASUS PRIME B550M-A Mainboard.jpg'),
                                              (2, '/image/MSI MPG X670E CARBON Mainboard.jpg'),
                                              (3, '/image/GIGABYTE B760M DS3H DDR4 Mainboard.jpg'),
                                              (4, '/image/ASRock A620M-HDV-M.2+ Mainboard.jpg'), -- Thay thế '/' bằng '-'
                                              (5, '/image/ASUS ROG STRIX Z790-E GAMING Mainboard.jpg'),
                                              (6, '/image/MSI PRO H610M-E DDR4 Mainboard.jpg'),
                                              (7, '/image/GIGABYTE X570 AORUS ELITE Mainboard.jpg'),
                                              (8, '/image/ASUS TUF GAMING B550-PLUS Mainboard.jpg'),
                                              (9, '/image/ASRock H510M-HDV Mainboard.jpg'),
                                              (10, '/image/MSI B450 TOMAHAWK MAX II Mainboard.jpg'),
                                              (11, '/image/GIGABYTE B650 AORUS ELITE Mainboard.jpg'),
                                              (12, '/image/ASUS PRIME H610M-K D4 Mainboard.jpg'),
                                              (13, '/image/ASRock Z690 PG RIPTIDE Mainboard.jpg'),
                                              (14, '/image/MSI MAG B550 TOMAHAWK Mainboard.jpg'),
                                              (15, '/image/GIGABYTE Z790 AORUS MASTER Mainboard.jpg'),
                                              (16, '/image/ASUS ROG CROSSHAIR X670E HERO Mainboard.jpg'),
                                              (17, '/image/MSI MPG B650M EDGE WIFI Mainboard.jpg'),
                                              (18, '/image/ASRock X570 PHANTOM GAMING 4 Mainboard.jpg'),
                                              (19, '/image/GIGABYTE A520M S2H Mainboard.jpg'),
                                              (20, '/image/ASUS PRIME B450M-K II Mainboard.jpg'),
                                              (21, '/image/MSI Z590 PRO WIFI Mainboard.jpg'),
                                              (22, '/image/GIGABYTE B365M DS3H Mainboard.jpg'),
                                              (23, '/image/ASRock B450M PRO4 Mainboard.jpg'),
                                              (24, '/image/ASUS PRIME X570-P Mainboard.jpg'),
                                              (25, '/image/MSI B650 TOMAHAWK WIFI Mainboard.jpg'),
                                              (26, '/image/GIGABYTE X399 AORUS XTREME Mainboard.jpg'),
                                              (27, '/image/ASRock Z790M-ITX WIFI Mainboard.jpg'),
                                              (28, '/image/ASUS ROG STRIX B650E-F GAMING WIFI Mainboard.jpg'),
                                              (29, '/image/MSI PRO X670-P WIFI Mainboard.jpg'),
                                              (30, '/image/GIGABYTE B550I AORUS PRO AX Mainboard.jpg'),
                                              (31, '/image/AMD Ryzen 5 5600X CPU.jpg'),
                                              (32, '/image/Intel Core i5-12400F CPU.jpg'),
                                              (33, '/image/Intel Core i7-13700K CPU.jpg'),
                                              (34, '/image/AMD Ryzen 9 7950X CPU.jpg'),
                                              (35, '/image/AMD Ryzen 7 5800X3D CPU.jpg'),
                                              (36, '/image/Intel Core i9-13900K CPU.jpg'),
                                              (37, '/image/AMD Ryzen 5 7600 CPU.jpg'),
                                              (38, '/image/Intel Core i3-12100F CPU.jpg'),
                                              (39, '/image/AMD Ryzen 7 7700 CPU.jpg'),
                                              (40, '/image/Intel Core i5-13600K CPU.jpg'),
                                              (41, '/image/AMD Ryzen 9 5950X CPU.jpg'),
                                              (42, '/image/Intel Core i9-12900KS CPU.jpg'),
                                              (43, '/image/AMD Ryzen 3 4100 CPU.jpg'),
                                              (44, '/image/Intel Core i5-14600K CPU.jpg'),
                                              (45, '/image/AMD Ryzen 5 5500 CPU.jpg'),
                                              (46, '/image/AMD Ryzen 9 7900X CPU.jpg'),
                                              (47, '/image/AMD Ryzen 7 7800X3D CPU.jpg'),
                                              (48, '/image/Intel Core i9-14900K CPU.jpg'),
                                              (49, '/image/Intel Core i7-12700F CPU.jpg'),
                                              (50, '/image/Intel Core i5-12400 CPU.jpg'),
                                              (51, '/image/Intel Core i3-13100 CPU.jpg'),
                                              (52, '/image/AMD Ryzen 5 4600G APU.jpg'),
                                              (53, '/image/AMD Ryzen 7 5700G APU.jpg'),
                                              (54, '/image/AMD Ryzen 3 5300G APU.jpg'),
                                              (55, '/image/Intel Core i5-11400F CPU.jpg'),
                                              (56, '/image/Intel Core i7-11700K CPU.jpg'),
                                              (57, '/image/AMD Ryzen 9 5900X CPU.jpg'),
                                              (58, '/image/AMD Ryzen 5 7500F CPU.jpg'),
                                              (59, '/image/Intel Core i9-11900K CPU.jpg'),
                                              (60, '/image/AMD Ryzen 3 3200G APU.jpg'),
                                              (61, '/image/NVIDIA GeForce RTX 3060 GPU.jpg'),
                                              (62, '/image/AMD Radeon RX 6600 XT GPU.jpg'),
                                              (63, '/image/NVIDIA GeForce RTX 4070 GPU.jpg'),
                                              (64, '/image/AMD Radeon RX 7900 XT GPU.jpg'),
                                              (65, '/image/NVIDIA GeForce RTX 4080 GPU.jpg'),
                                              (66, '/image/AMD Radeon RX 6800 GPU.jpg'),
                                              (67, '/image/NVIDIA GeForce RTX 3050 GPU.jpg'),
                                              (68, '/image/AMD Radeon RX 6500 XT GPU.jpg'),
                                              (69, '/image/NVIDIA GeForce RTX 4070 Ti GPU.jpg'),
                                              (70, '/image/AMD Radeon RX 7800 XT GPU.jpg'),
                                              (71, '/image/NVIDIA GeForce RTX 4060 GPU.jpg'),
                                              (72, '/image/AMD Radeon RX 6700 XT GPU.jpg'),
                                              (73, '/image/NVIDIA GeForce GTX 1660 SUPER GPU.jpg'),
                                              (74, '/image/AMD Radeon RX 5600 XT GPU.jpg'),
                                              (75, '/image/NVIDIA GeForce RTX 2080 SUPER GPU.jpg'),
                                              (76, '/image/NVIDIA GeForce RTX 4090 GPU.jpg'),
                                              (77, '/image/AMD Radeon RX 7600 GPU.jpg'),
                                              (78, '/image/NVIDIA GeForce RTX 4060 Ti GPU.jpg'),
                                              (79, '/image/AMD Radeon RX 6950 XT GPU.jpg'),
                                              (80, '/image/NVIDIA GeForce RTX 3070 GPU.jpg'),
                                              (81, '/image/NVIDIA GeForce RTX 3090 GPU.jpg'),
                                              (82, '/image/NVIDIA GeForce RTX 4070 SUPER GPU.jpg'),
                                              (83, '/image/AMD Radeon RX 7700 XT GPU.jpg'),
                                              (84, '/image/AMD Radeon RX 6800 XT GPU.jpg'),
                                              (85, '/image/NVIDIA GeForce RTX 2060 GPU.jpg'),
                                              (86, '/image/NVIDIA GeForce GTX 1650 SUPER GPU.jpg'),
                                              (87, '/image/AMD Radeon RX 5500 XT GPU.jpg'),
                                              (88, '/image/NVIDIA GeForce RTX 2080 Ti GPU.jpg'),
                                              (89, '/image/NVIDIA GeForce RTX 4060 SUPER GPU.jpg'),
                                              (90, '/image/AMD Radeon RX 6400 GPU.jpg'),
                                              (91, '/image/Corsair Vengeance LPX 16GB RAM.jpg'),
                                              (92, '/image/G.Skill Ripjaws V 16GB RAM.jpg'),
                                              (93, '/image/Kingston Fury Beast 8GB RAM.jpg'),
                                              (94, '/image/Crucial Ballistix 32GB RAM.jpg'),
                                              (95, '/image/Teamgroup T-Force Vulcan Z 16GB RAM.jpg'),
                                              (96, '/image/G.Skill Trident Z RGB 16GB RAM.jpg'),
                                              (97, '/image/Corsair Dominator Platinum RGB 32GB RAM.jpg'),
                                              (98, '/image/Kingston Fury Beast 32GB RAM.jpg'),
                                              (99, '/image/Crucial Pro 16GB RAM.jpg'),
                                              (100, '/image/G.Skill Ripjaws V 32GB RAM 4000MHz.jpg'),
                                              (101, '/image/Corsair Vengeance RGB Pro 16GB RAM.jpg'),
                                              (102, '/image/Teamgroup T-Create Expert 32GB RAM.jpg'),
                                              (103, '/image/Kingston Fury Renegade 16GB RAM.jpg'),
                                              (104, '/image/G.Skill Trident Z Royal Silver 32GB RAM.jpg'),
                                              (105, '/image/Corsair Vengeance LPX 32GB RAM 3600MHz.jpg'),
                                              (106, '/image/Corsair Vengeance 32GB DDR5 RAM.jpg'),
                                              (107, '/image/G.Skill Trident Z5 RGB 32GB DDR5 RAM.jpg'),
                                              (108, '/image/Kingston Fury Beast 16GB DDR5 RAM.jpg'),
                                              (109, '/image/Crucial Pro 32GB DDR5 RAM.jpg'),
                                              (110, '/image/Teamgroup T-Force Delta RGB 32GB DDR5 RAM.jpg'),
                                              (111, '/image/Corsair Dominator Platinum RGB 32GB DDR5 RAM.jpg'),
                                              (112, '/image/G.Skill Ripjaws S5 32GB DDR5 RAM.jpg'),
                                              (113, '/image/Kingston Fury Renegade 32GB DDR5 RAM 6400MHz.jpg'),
                                              (114, '/image/G.Skill Trident Z5 RGB 64GB DDR5 RAM.jpg'),
                                              (115, '/image/Corsair Vengeance RGB 32GB DDR5 RAM.jpg'),
                                              (116, '/image/Crucial 16GB DDR5 4800MHz RAM.jpg'),
                                              (117, '/image/Teamgroup T-Force Xtreem 32GB DDR5 RAM 7600MHz.jpg'),
                                              (118, '/image/Kingston Fury Beast 64GB DDR5 RAM.jpg'),
                                              (119, '/image/G.Skill Flare X5 32GB DDR5 RAM CL30.jpg'),
                                              (120, '/image/Corsair Vengeance 64GB DDR5 5200MHz RAM.jpg'),
                                              (121, '/image/Samsung 980 Pro 1TB SSD.jpg'),
                                              (122, '/image/WD Black SN850X 1TB SSD.jpg'),
                                              (123, '/image/Crucial P5 Plus 1TB SSD.jpg'),
                                              (124, '/image/Kingston KC3000 1TB SSD.jpg'),
                                              (125, '/image/Samsung 970 Evo Plus 500GB SSD.jpg'),
                                              (126, '/image/WD Blue SN570 1TB SSD.jpg'),
                                              (127, '/image/SK Hynix Platinum P41 2TB SSD.jpg'),
                                              (128, '/image/Crucial P3 1TB SSD.jpg'),
                                              (129, '/image/Samsung 990 Pro 2TB SSD.jpg'),
                                              (130, '/image/Kingston NV2 500GB SSD.jpg'),
                                              (131, '/image/WD Black SN770 500GB SSD.jpg'),
                                              (132, '/image/Sabrent Rocket 4 Plus 1TB SSD.jpg'),
                                              (133, '/image/Gigabyte AORUS Gen4 7000s 1TB SSD.jpg'),
                                              (134, '/image/Corsair MP600 PRO LPX 1TB SSD.jpg'),
                                              (135, '/image/Adata XPG Gammix S70 Blade 1TB SSD.jpg'),
                                              (136, '/image/Samsung 870 Evo 1TB SATA SSD.jpg'),
                                              (137, '/image/Crucial MX500 1TB SATA SSD.jpg'),
                                              (138, '/image/WD Blue 500GB SATA SSD.jpg'),
                                              (139, '/image/Kingston A400 480GB SATA SSD.jpg'),
                                              (140, '/image/Samsung 870 QVO 2TB SATA SSD.jpg'),
                                              (141, '/image/SanDisk Ultra 3D 1TB SATA SSD.jpg'),
                                              (142, '/image/Crucial BX500 240GB SATA SSD.jpg'),
                                              (143, '/image/Gigabyte SSD 120GB SATA SSD.jpg'),
                                              (144, '/image/Seagate Barracuda 1TB HDD.jpg'),
                                              (145, '/image/WD Blue 2TB HDD.jpg'),
                                              (146, '/image/Seagate IronWolf 4TB NAS HDD.jpg'),
                                              (147, '/image/WD Black 4TB HDD.jpg'),
                                              (148, '/image/Toshiba P300 1TB HDD.jpg'),
                                              (149, '/image/Seagate SkyHawk 2TB HDD.jpg'),
                                              (150, '/image/WD Purple 4TB HDD.jpg'),
                                              (151, '/image/Cooler Master MasterBox Q300L Case.jpg'),
                                              (152, '/image/Corsair Carbide Series 175R RGB Case.jpg'),
                                              (153, '/image/Thermaltake Versa H18 Case.jpg'),
                                              (154, '/image/NZXT H510 Matte White Case.jpg'),
                                              (155, '/image/Phanteks Eclipse P300A Mesh Case.jpg'),
                                              (156, '/image/Fractal Design Meshify C TG Case.jpg'),
                                              (157, '/image/Lian Li Lancool 215 Black Case.jpg'),
                                              (158, '/image/Cooler Master MasterBox TD500 Mesh ARGB Case.jpg'),
                                              (159, '/image/Corsair 4000D Airflow Black Case.jpg'),
                                              (160, '/image/NZXT H5 Flow Black Case.jpg'),
                                              (161, '/image/ASUS TUF Gaming GT301 Case.jpg'),
                                              (162, '/image/Phanteks Eclipse G360A Black Case.jpg'),
                                              (163, '/image/Lian Li O11 Dynamic EVO Black Case.jpg'),
                                              (164, '/image/Corsair 5000D Airflow White Case.jpg'),
                                              (165, '/image/Fractal Design Torrent Black TG Case.jpg'),
                                              (166, '/image/NZXT H7 Flow White Case.jpg'),
                                              (167, '/image/Cooler Master HAF 500 Black Case.jpg'),
                                              (168, '/image/Phanteks Enthoo Evolv X Glass Case.jpg'),
                                              (169, '/image/Lian Li Lancool III RGB Black Case.jpg'),
                                              (170, '/image/Corsair 7000D Airflow Black Case.jpg'),
                                              (171, '/image/Cooler Master Cosmos C700M Case.jpg'),
                                              (172, '/image/Thermaltake The Tower 900 Black Case.jpg'),
                                              (173, '/image/Fractal Design Define 7 XL Case.jpg'),
                                              (174, '/image/Cooler Master MasterBox NR200P White Case.jpg'),
                                              (175, '/image/Lian Li A4-H2O Black Case.jpg'),
                                              (176, '/image/NZXT H1 (V2) Matte Black Case.jpg'),
                                              (177, '/image/Fractal Design Terra Jade Case.jpg'),
                                              (178, '/image/ASUS ROG Strix Helios White Case.jpg'),
                                              (179, '/image/Thermaltake Core P3 TG Black Case.jpg'),
                                              (180, '/image/Hyte Y60 Black Case.jpg'),
                                              (181, '/image/Corsair CV550 PSU.jpg'),
                                              (182, '/image/Cooler Master MWE Bronze V2 650W PSU.jpg'),
                                              (183, '/image/Seasonic S12III 550W PSU.jpg'),
                                              (184, '/image/Thermaltake Smart BX1 650W PSU.jpg'),
                                              (185, '/image/EVGA 600 W1 PSU.jpg'),
                                              (186, '/image/be quiet! System Power 9 500W PSU.jpg'),
                                              (187, '/image/Corsair CX650M 650W PSU.jpg'),
                                              (188, '/image/Corsair RM750e 750W PSU.jpg'),
                                              (189, '/image/Seasonic Focus Plus Gold 850W PSU.jpg'),
                                              (190, '/image/Cooler Master MWE Gold V2 850W PSU.jpg'),
                                              (191, '/image/ASUS ROG Strix 850G PSU.jpg'),
                                              (192, '/image/Thermaltake Toughpower GF1 750W PSU.jpg'),
                                              (193, '/image/EVGA SuperNOVA 850 G6 PSU.jpg'),
                                              (194, '/image/be quiet! Pure Power 11 FM 750W PSU.jpg'),
                                              (195, '/image/Corsair RM850x SHIFT 850W PSU.jpg'),
                                              (196, '/image/NZXT C850 Gold V2 850W PSU.jpg'),
                                              (197, '/image/Corsair RM1000e 1000W PSU.jpg'),
                                              (198, '/image/Seasonic PRIME TX-1000 PSU.jpg'),
                                              (199, '/image/Cooler Master V1300 Platinum 1300W PSU.jpg'),
                                              (200, '/image/ASUS ROG Thor 1200P2 PSU.jpg'),
                                              (201, '/image/EVGA SuperNOVA 1600 P+ PSU.jpg'),
                                              (202, '/image/be quiet! Dark Power Pro 12 1500W PSU.jpg'),
                                              (203, '/image/Thermaltake Toughpower PF1 1200W PSU.jpg'),
                                              (204, '/image/Corsair SF750 750W SFX PSU.jpg'),
                                              (205, '/image/Cooler Master V850 SFX Gold 850W PSU.jpg'),
                                              (206, '/image/Lian Li SP850 850W SFX PSU.jpg'),
                                              (207, '/image/Deepcool PQ1000M 1000W PSU.jpg'),
                                              (208, '/image/FSP Hydro G Pro 1000W PSU.jpg'),
                                              (209, '/image/MSI MPG A850G 850W PSU PCIE5.jpg'),
                                              (210, '/image/Antec NeoECO Gold Zen 700W PSU.jpg'),
                                              (211, '/image/Cooler Master Hyper 212 Spectrum V3 Cooler.jpg'),
                                              (212, '/image/Noctua NH-D15 chromax.black Cooler.jpg'),
                                              (213, '/image/Deepcool AK400 Performance Cooler.jpg'),
                                              (214, '/image/Thermalright Phantom Spirit 120 SE ARGB Cooler.jpg'),
                                              (215, '/image/Deepcool AK620 Black Cooler.jpg'),
                                              (216, '/image/Noctua NH-U12A Cooler.jpg'),
                                              (217, '/image/Cooler Master MasterAir MA624 Stealth Cooler.jpg'),
                                              (218, '/image/Noctua NH-L9i-17xx Cooler.jpg'),
                                              (219, '/image/Thermalright Assassin X 120 Refined SE Cooler.jpg'),
                                              (220, '/image/be quiet! Dark Rock Pro 4 Cooler.jpg'),
                                              (221, '/image/Cooler Master MasterLiquid 240L Core ARGB AIO.jpg'),
                                              (222, '/image/Corsair H150i Elite Capellix XT White AIO.jpg'),
                                              (223, '/image/NZXT Kraken 240 RGB Black AIO.jpg'),
                                              (224, '/image/Lian Li Galahad II Trinity 360 ARGB AIO.jpg'),
                                              (225, '/image/Deepcool LT720 WH 360mm AIO.jpg'),
                                              (226, '/image/Arctic Liquid Freezer II 280 AIO.jpg'),
                                              (227, '/image/Corsair H100i RGB PRO XT AIO.jpg'),
                                              (228, '/image/ASUS ROG RYUJIN III 360 ARGB AIO.jpg'),
                                              (229, '/image/NZXT Kraken Elite 360 RGB White AIO.jpg'),
                                              (230, '/image/Thermalright Frozen Notte 360 Black ARGB AIO.jpg');
